services:
  - type: web
    name: renaper-service
    env: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: cd ./publish && dotnet RenaperService.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:5000